### ISSUE TITLE
Strange plant bug

### ISSUE THREAD

**Issue by pettrs** [YvesW/random-event-hider#3] opened 2023-01-18 20:16 UTC
the strange appears to be flashing in and out of hiding
https://user-images.githubusercontent.com/75093127/213285290-0f7c0f8f-bb90-49e2-b468-d1d856642bf3.mp4

**Comment by YvesW** [comment] 2023-01-18 20:49
I've changed around some of the code so it might be fixed in my latest dev build, but I've had multiple strange plants and have not been able to reproduce this. It looks like it happens while the plant is growing? It should still have the same NpcId though which means that
```
if (npcId == NpcID.STRANGE_PLANT) {
			return hideAllStrangePlant;
		}
```
should hide it though.
Will keep this open and will keep an eye out for it.

**Comment by pettrs** [comment] 2023-01-20 17:08
Still experiencing this same bug but with other random events 

https://user-images.githubusercontent.com/75093127/213760798-87f607e2-998f-43fd-945c-e15df2b6b8ad.mp4


https://user-images.githubusercontent.com/75093127/213760864-ea2aa587-5e8e-44fe-aa82-46e4895df245.mp4

**Comment by YvesW** [comment] 2023-01-20 21:40
The code hasn't changed, so makes sense it hasn't changed (PR waiting for approval). However, I've never had this bug myself. Are you playing on the official runelite client, or some shady fork?

**Comment by pettrs** [comment] 2023-01-20 23:50
I'm playing the official runelite client through the Jagex launcher

**Comment by pettrs** [comment] 2023-01-20 23:55
nevermind
https://user-images.githubusercontent.com/75093127/213825327-120381b6-9f44-4369-832f-984dd5697ad3.mp4

**Comment by YvesW** [comment] 2023-01-21 03:37
Might be related to you being in combat; I'll have to check in the latest devbuild and also in combat. When I'm in combat (raids), randoms usually can't spawn. I'll let you know when the PR gets merged and then you can check again.

**Comment by YvesW** [comment] 2023-01-21 10:06
@pettrs Could you upload some screenshots? That might confirm my hypothesis (race-y behaviour).
1. A screenshot of the settings of Random Event Hider
2. A screenschot of the settings of core (default) Entity Hider
Thanks in advance!

**Comment by pettrs** [comment] 2023-01-22 17:13
![image](https://user-images.githubusercontent.com/75093127/213929749-6297d705-36f9-4871-82ff-9b6f566f8de0.png)
![image](https://user-images.githubusercontent.com/75093127/213929756-92352c79-a079-4c22-b661-69528bf40ff8.png)

![image](https://user-images.githubusercontent.com/75093127/213929773-2dff5811-edcf-4921-8812-bf562acb0eaf.png)

I have entity hider disabled, and it's still happening

**Comment by pettrs** [comment] 2023-01-22 17:27
alright, I think I've been able to source down the issue. I noticed when I hide attackers (also what random events go under) it seems like when the attack isn't attacking you, like a random event, it flickers.

https://user-images.githubusercontent.com/75093127/213930502-05ccbe82-8273-486d-9172-4f616226a2ee.mp4

**Comment by YvesW** [comment] 2023-01-22 18:40
The client does indeed not know the difference between "combat" and "interaction", but it's really weird that you also see the attackers and even the 2D elements of players flicker. 3rd party plugins only have the ability to use the shouldDraw function from the RL API, so I'm afraid that's borked for you for some reason, e.g. different plugin interfering(?), bad implementation if you were on a fork etc. If you can get the flickering consistently with entity hider enabled (e.g. Npcs, 2D elements of players), I'd suggest trying safe mode for a while and seeing if it persists.
From RL discord:

> Launch RuneLite in safe mode using the following command:
> `"%localappdata%\runelite\runelite.exe" --clientargs --safe-mode`
> 
> This temporarily disables all 3rd party plugins which will allow you to confirm the issue is caused by the plugin and isn't a core RuneLite issue.
> 
> If the issue is caused by a 3rd party plugin, you should isolate which plugin it is and then uninstall the plugin.
> 

I'm afraid that with the current info, it looks like it's not something I can fix (underlying problem, not a problem of this specific plugin), at least not while I haven't been able to recreate it myself (my entity hider also works perfectly). I'll let you know when the latest update has been merged; maybe that that'll fix it but I doubt it. I'll also try to keep an eye out myself to see if I can recreate this.

**Comment by ZeiZeiii** [comment] 2023-01-30 17:19
Im currently having this same issue with different random events as well.

**Comment by ZeiZeiii** [comment] 2023-01-31 08:16
@YvesW same kind of flickering like Pettrs has, with multiple different events. Core Entity Hider works as intended.

**Comment by ZeiZeiii** [comment] 2023-01-31 18:07
In both. While standing still and on move as well. Thank you!

Jan 31, 2023, 19:08 by ***@***.***:

**Comment by YvesW** [comment] 2023-02-03 14:47
@pettrs @ZeiZeiii The update has been merged; restart your client for it to take effect. As a sidenote, I tried to replicate it while afking some vyrewatch sentinels earlier and I could not get the random events to flicker at all.

**Comment by ZeiZeiii** [comment] 2023-02-05 10:48
Seems to be working accordingly now. Thank you sir! :)

Feb 3, 2023, 16:47 by ***@***.***:

**Closed** 2023-03-06 21:25 UTC
